### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by iyenal** [Kinnay/SM3DW-Level-Editor#5]
Can you add the textures support of the fmdt part and the export to a 3d model format (obj,dae...) please. Thank you

**Comment by kinnay** [comment]
Models can be converted to obj with this tool: https://github.com/Kinnay/Wii-U-FMDL-Parser
That tool also converts textures, but it requires you to download TexConv2, a tool from the Cafe SDK, because textures use a complex swizzling algorithm and I haven't been able to unswizzle them. This SM3DW editor doesn't supports textures, because I don't want to force people to download TexConv2 to use the editor.
